### ISSUE TITLE
Uploads from rdz_ttgo_sonde not saving?

### ISSUE THREAD

**Issue by HoshenKadosh** [projecthorus/sondehub-infra#41] opened 2021-12-26 23:20 UTC
Hi, I have encountered a very weird bug recently.

Some frames uploaded from an rdz_ttgo_sonde station, are shown on sondehub **only if at the time of upload you are in the site** (which means it's sent by the websocket). but after reloading sondehub (requesting /telemetry), it's missing and not showing the recent frames uploaded by the rdz_ttgo_sonde. 

I assume its a sondehub-infra issue and not a rdz_ttgo_sonde issue since the data is ending up at the API.

I saw this today after recovering a sonde that was last received by an auto_rx station at a high altitude, and after I came to the landing zone and used rdz_ttgo_sonde which uploaded frames of the sonde in the ground, it's missing after refreshing sondehub. 

screenshot of sondehub that was opened when the frames were uploaded (showing the recent data by a rdz_ttgo_sonde station):
![image](https://user-images.githubusercontent.com/47646557/147421639-52aa874f-8831-43ee-b771-aef53ac97696.png)
screenshot after refreshing sondehub (recent rdz_ttgo_sonde data missing):
![image](https://user-images.githubusercontent.com/47646557/147421728-e6fe9cba-cbee-49e7-8d0f-d84d8582a566.png)

I hope I was clear in describing the issue. Thanks.

**Comment by darksidelemm** [comment] 2021-12-27 00:07
Unsure what the issue is here. If the data ended up on the tracker, then it's in the database....

**Comment by eben80** [comment] 2021-12-29 09:14
I have something similar from my rdz_ttgo all of a sudden. I've tried to look if my receiver and data is listed in the DB but the Swagger UI representation is not as I remember it before. Has something changed there?

**Comment by darksidelemm** [comment] 2021-12-29 23:42
Yeah something has broken with that swagger generator, it wont accept the swagger file in the URL. Not sure what's going on. 

If you paste in `https://raw.githubusercontent.com/projecthorus/sondehub-infra/main/swagger.yaml` into the box at the top of the page and click 'Explore' it will load it.

**Comment by LukePrior** [comment] 2021-12-30 01:41
I'm noticing the same thing with the data appearing on the site via websockets but not getting saved to Elastic Search.

**Comment by darksidelemm** [comment] 2021-12-30 02:09
My guess is there's something wrong in the ingestion pipeline.

**Comment by TheSkorm** [comment] 2021-12-30 04:09
This was a tricky one to debug. Historically we ignored elasticsearch mapper errors (when fields are invalid) because we didn't do any bounds checking for values. Since then, we have implemented some basic checks that prevent bad data getting to that point in the pipeline. 

Unfortunately we weren't handling `uploader_position` being set to nulls when uploading to elasticsearch and we never noticed due to the errors being ignored. I'm not sure how long this has been the case, but it should now be fixed as of 94b695e907301dcdd7a9d2e7041b5b7cc9bd3e15

<img width="849" alt="image" src="https://user-images.githubusercontent.com/234867/147720968-0d4bf69d-1bfa-40ae-8da0-1f0d9626c142.png">

This would be only impacting clients that the uploader position was sent as `[null,null,null]` but rather than excluded completely or as just `null`

Hopefully we catch errors like this in the future. I'll leave the mapper errors enabled and monitor to see if we can keep this configuration of ignoring the,.

**Comment by TheSkorm** [comment] 2021-12-30 04:12
The issue we've had in the past is that a bad value will prevent the record being uploaded to elasticsearch, triggering an error and forcing that batch into the queue again, basically getting stuck processing forever. At the very least we should log these errors, but I'll see how it goes

**Closed** 2022-01-01 06:47 UTC
